/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffQuotationsRouteImport } from './routes/staff/quotations'
import { Route as StaffOrdersRouteImport } from './routes/staff/orders'
import { Route as StaffInvoicesRouteImport } from './routes/staff/invoices'
import { Route as PartnerQuotationsRouteImport } from './routes/partner/quotations'
import { Route as PartnerOrdersRouteImport } from './routes/partner/orders'
import { Route as PartnerInvoicesRouteImport } from './routes/partner/invoices'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRecycleBinRouteImport } from './routes/admin/recycle-bin'
import { Route as AdminQuotationsRouteImport } from './routes/admin/quotations'
import { Route as AdminPartyMasterRouteImport } from './routes/admin/party-master'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminItemsRouteImport } from './routes/admin/items'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQuotationsRoute = StaffQuotationsRouteImport.update({
  id: '/staff/quotations',
  path: '/staff/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/staff/orders',
  path: '/staff/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInvoicesRoute = StaffInvoicesRouteImport.update({
  id: '/staff/invoices',
  path: '/staff/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerQuotationsRoute = PartnerQuotationsRouteImport.update({
  id: '/partner/quotations',
  path: '/partner/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOrdersRoute = PartnerOrdersRouteImport.update({
  id: '/partner/orders',
  path: '/partner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerInvoicesRoute = PartnerInvoicesRouteImport.update({
  id: '/partner/invoices',
  path: '/partner/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecycleBinRoute = AdminRecycleBinRouteImport.update({
  id: '/admin/recycle-bin',
  path: '/admin/recycle-bin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotationsRoute = AdminQuotationsRouteImport.update({
  id: '/admin/quotations',
  path: '/admin/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartyMasterRoute = AdminPartyMasterRouteImport.update({
  id: '/admin/party-master',
  path: '/admin/party-master',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/party-master': typeof AdminPartyMasterRoute
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/recycle-bin': typeof AdminRecycleBinRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/partner/invoices': typeof PartnerInvoicesRoute
  '/partner/orders': typeof PartnerOrdersRoute
  '/partner/quotations': typeof PartnerQuotationsRoute
  '/staff/invoices': typeof StaffInvoicesRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/party-master': typeof AdminPartyMasterRoute
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/recycle-bin': typeof AdminRecycleBinRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/partner/invoices': typeof PartnerInvoicesRoute
  '/partner/orders': typeof PartnerOrdersRoute
  '/partner/quotations': typeof PartnerQuotationsRoute
  '/staff/invoices': typeof StaffInvoicesRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/admin': typeof AdminIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/party-master': typeof AdminPartyMasterRoute
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/recycle-bin': typeof AdminRecycleBinRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/partner/invoices': typeof PartnerInvoicesRoute
  '/partner/orders': typeof PartnerOrdersRoute
  '/partner/quotations': typeof PartnerQuotationsRoute
  '/staff/invoices': typeof StaffInvoicesRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/party-master'
    | '/admin/quotations'
    | '/admin/recycle-bin'
    | '/admin/settings'
    | '/admin/users'
    | '/partner/invoices'
    | '/partner/orders'
    | '/partner/quotations'
    | '/staff/invoices'
    | '/staff/orders'
    | '/staff/quotations'
    | '/admin/'
    | '/partner/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/party-master'
    | '/admin/quotations'
    | '/admin/recycle-bin'
    | '/admin/settings'
    | '/admin/users'
    | '/partner/invoices'
    | '/partner/orders'
    | '/partner/quotations'
    | '/staff/invoices'
    | '/staff/orders'
    | '/staff/quotations'
    | '/admin'
    | '/partner'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/party-master'
    | '/admin/quotations'
    | '/admin/recycle-bin'
    | '/admin/settings'
    | '/admin/users'
    | '/partner/invoices'
    | '/partner/orders'
    | '/partner/quotations'
    | '/staff/invoices'
    | '/staff/orders'
    | '/staff/quotations'
    | '/admin/'
    | '/partner/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPartyMasterRoute: typeof AdminPartyMasterRoute
  AdminQuotationsRoute: typeof AdminQuotationsRoute
  AdminRecycleBinRoute: typeof AdminRecycleBinRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  PartnerInvoicesRoute: typeof PartnerInvoicesRoute
  PartnerOrdersRoute: typeof PartnerOrdersRoute
  PartnerQuotationsRoute: typeof PartnerQuotationsRoute
  StaffInvoicesRoute: typeof StaffInvoicesRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffQuotationsRoute: typeof StaffQuotationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/quotations': {
      id: '/staff/quotations'
      path: '/staff/quotations'
      fullPath: '/staff/quotations'
      preLoaderRoute: typeof StaffQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/staff/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/invoices': {
      id: '/staff/invoices'
      path: '/staff/invoices'
      fullPath: '/staff/invoices'
      preLoaderRoute: typeof StaffInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/quotations': {
      id: '/partner/quotations'
      path: '/partner/quotations'
      fullPath: '/partner/quotations'
      preLoaderRoute: typeof PartnerQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/orders': {
      id: '/partner/orders'
      path: '/partner/orders'
      fullPath: '/partner/orders'
      preLoaderRoute: typeof PartnerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/invoices': {
      id: '/partner/invoices'
      path: '/partner/invoices'
      fullPath: '/partner/invoices'
      preLoaderRoute: typeof PartnerInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recycle-bin': {
      id: '/admin/recycle-bin'
      path: '/admin/recycle-bin'
      fullPath: '/admin/recycle-bin'
      preLoaderRoute: typeof AdminRecycleBinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotations': {
      id: '/admin/quotations'
      path: '/admin/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AdminQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/party-master': {
      id: '/admin/party-master'
      path: '/admin/party-master'
      fullPath: '/admin/party-master'
      preLoaderRoute: typeof AdminPartyMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPartyMasterRoute: AdminPartyMasterRoute,
  AdminQuotationsRoute: AdminQuotationsRoute,
  AdminRecycleBinRoute: AdminRecycleBinRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  PartnerInvoicesRoute: PartnerInvoicesRoute,
  PartnerOrdersRoute: PartnerOrdersRoute,
  PartnerQuotationsRoute: PartnerQuotationsRoute,
  StaffInvoicesRoute: StaffInvoicesRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffQuotationsRoute: StaffQuotationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
